name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "${DOCKER_DN}", custom_domain = true },
  { pattern = "${QUAY_DN}", custom_domain = true },
  { pattern = "${GCR_DN}", custom_domain = true },
  { pattern = "${K8S_GCR_DN}", custom_domain = true },
  { pattern = "${K8S_DN}", custom_domain = true },
  { pattern = "${GHCR_DN}", custom_domain = true },
  { pattern = "${CLOUDSMITH_DN}", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "${DOCKER_STAGING_DN}", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
